# Generated by Django 2.0 on 2017-12-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Stock Symbol')),
                ('price', models.FloatField(verbose_name='Most Recent Price')),
            ],
        ),
    ]
